services:
  - type: web
    name: roman-golovin-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: YANDEX_GPT_API_KEY
        sync: false
      - key: YANDEX_FOLDER_ID
        sync: false